#!/usr/bin/env sh
# Auto-generated by clipress init — do not edit manually.
# Discovers the clipress installation at runtime.

# 1. clipress on PATH (pipx, brew, system pip, uv tool install, conda …)
if command -v clipress >/dev/null 2>&1; then
    exec clipress hook
fi

# 2. Common single-user install locations (when PATH is narrow)
for _p in \
    "$HOME/.local/bin/clipress" \
    "$HOME/.local/share/uv/tools/clipress/bin/clipress" \
    "/usr/local/bin/clipress" \
    "/usr/bin/clipress"
do
    if [ -x "$_p" ]; then
        exec "$_p" hook
    fi
done

# 3. Python module fallback — works when clipress is installed in a venv
#    reachable by python3/python but not exported as a console script.
for _py in python3 python; do
    if command -v "$_py" >/dev/null 2>&1; then
        if "$_py" -c "import clipress" >/dev/null 2>&1; then
            exec "$_py" -m clipress.hooks.post_tool_use
        fi
    fi
done

# 4. Not found — exit 0 so the agent is never blocked.
exit 0
